### ISSUE TITLE
Access denied when trying to get into symlink directory

### ISSUE THREAD

**Issue by jimsmt** [alez-repos/ztef8648p#1]
Hi, thank you for the great tutorial  on https://bandaancha.eu/, I tried to reply there but they don't allow new user registration.

I'm not using F8648P, but a very similar model, software version is  V2.0.6P1T8. The vulnerability of samba symlink has been fixed, smbd version is 4.5.1, when trying to get into the soft-linked directory, I get the access denied error message.

So I wonder if there's any other vulnerability to use?

Thanks

**Comment by alez-repos** [comment]
Everything here and on the tutorial has been tried on the F8648P, specifically on V2.0.12P7N3 version. I cant guarantee this to work on other router models as I don't have them to test or to find new methods, sadly.
